
# This is a basic workflow to help you get started with Actions

name: Check package v2

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 8 * * 5' # every friday AM 8:00

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  npm:
     runs-on: ubuntu-latest
     steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Run npm install
        run: npm install
      
      - uses: MeilCli/npm-update-check-action@v4.0.0
        name: Run npm update
        with:
          output_text_style: long
        id: outdated
      
      - uses: JasonEtco/create-an-issue@v2
        name: Create or update issue if outdated packages
        if: steps.outdated.outputs.has_npm_update == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BODY: ${{ steps.outdated.outputs.npm_update_text }}
        with:
          filename: .github/npm-update-template.md
          update_existing: true
          if: steps.outdated.outputs.has_npm_update == 'true'
        id: create-issue
       
      - if: steps.outdated.outputs.has_npm_update == 'true'
        run: 'echo Created or updated ${{ steps.create-issue.outputs.url }}'
