# This is a basic workflow to help you get started with Actions

name: Check package

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 8 * * 5' # every friday AM 8:00

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  npm:
     runs-on: ubuntu-latest
     steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Run npm install
        run: npm install
      
      - uses: MeilCli/npm-update-check-action@v4.0.0
        name: Run npm update
        with:
          output_text_style: long
        id: outdated
      
      - uses: nashmaniac/create-issue-action@v1.1
        name: Create issue if outdated packages
        if: steps.outdated.outputs.has_npm_update == 'true'
        with:
          title: Update npm packages
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: Bug
          body: ${{ steps.outdated.outputs.npm_update_text }}
